### ISSUE TITLE
Edge case: possible encoder failure

### ISSUE THREAD

**Issue by WizardCM** [obsproject/loganalyzer#1]
19:23:57.769: socket_thread_windows: Received FD_CLOSE, 19135 ms since last send (buffer: 529690 / 532480)
19:23:57.769: socket_thread_windows: Aborting due to FD_CLOSE, error 10053

Source: https://gist.github.com/anonymous/b7982db67d6390ff34c43f97bbe2c5e5

**Comment by sophieschi** [comment]
I'm not sure if this is still applicable with new NVENC being default.
