### ISSUE TITLE
32bit windows wrongfully fired

### ISSUE THREAD

**Issue by flaeri** [obsproject/loganalyzer#122]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Version (Other)

OBS 29.0.0-456-g724dc494f

### OBS Studio Log URL

https://obsproject.com/logs/Qn6Xgb1PT0muSaTE

### Expected Behavior

I expect the check32bitOn64bit check to fail (not enter the if).

### Current Behavior

It enters the if.

### Steps to Reproduce

1. Use a recent OBS version, after the 64bit tag was removed the "OBS" line
2. Upload log
3. Put log into log analyzer

### Anything else we should know?

`if (len(winVersion) > 0 and '64-bit' in winVersion[0] and '64-bit' not in obsVersion and '64bit' not in obsVersion):`

I *think* the 64bit line was removed from the log via https://github.com/obsproject/obs-studio/pull/8371

Now just says `OBS 29.0.0-456-g724dc494f (windows)`

I could be wrong, and this is just for git builds, and not release.

**Comment by flaeri** [comment]
Not sure how to attack this, short of removing the check. You could gate it to version, but seems meh. 32bit is more or less dead now, so I feel like its sane to just remove it.

I'll probably PR its removal soon unless anyone else has any other suggestions.

**Comment by RytoEX** [comment]
As an aside, it was here:
https://github.com/obsproject/obs-studio/pull/8267

The PR probably had the same problem that https://github.com/obsproject/obs-studio/pull/8371 had where the changed function affected far more than just the title bar and About dialog.

**Comment by RytoEX** [comment]
This should have been fixed by the obs-studio revert linked above and #126 .

**Comment by RytoEX** [comment]
Closing per above.
