### ISSUE TITLE
Win 10 Gaming Features

### ISSUE THREAD

**Issue by Gol-D-Ace** [obsproject/loganalyzer#19]
It's possible that Win 10 Gaming Features might not be detected.
It's possible to be in the following state:
```
Game Bar: Off
Game DVR: Off
Game DVR Background Recording: Off
```
Being in this state can mean that Game Mode is still on.
``Game Mode: On/Off``

**Comment by sophieschi** [comment]
Do you have an example log file I could test this issue with?

**Comment by Gol-D-Ace** [comment]
Not sure if this is still relevant with Microsoft's changes to game mode.
I just disabled the game bar and let game mode active.
https://obsproject.com/logs/cynxSIYFcuSs0MgF

**Comment by WizardCM** [comment]
Fixed via https://github.com/obsproject/loganalyzer/commit/43cbc7e3fd5c304e76932e8aa69d4a052eee7fca
