### ISSUE TITLE
Lost frames and crashing many times

### ISSUE THREAD

**Issue by rodrigoterra** [obsproject/loganalyzer#53]
https://obsproject.com/logs/Nl3DW9027BNIuQPJ
https://obsproject.com/logs/jD3JvDr9PFzu9Woe

**Comment by Fenrirthviti** [comment]
It is not appropriate to ask for support on the log analyzer repo. You need to submit the logs to the actual analyzer if you're looking to have them analyzed.

https://obsproject.com/analyzer/
