### ISSUE TITLE
OBS Crash

### ISSUE THREAD

**Issue by P-h-r-e-a-k** [obsproject/loganalyzer#57]
[Crash 2020-06-26 12-52-39.txt](https://github.com/obsproject/loganalyzer/files/4836894/Crash.2020-06-26.12-52-39.txt)

**Comment by Fenrirthviti** [comment]
This is not the appropriate place to report crash logs. Please use the forums or discord instead.

https://obsproject.com/help

Your crash appears to be due to system instability. Try updating your BIOS and Ryzens were known for this crash without updated BIOS.
