### ISSUE TITLE
OBS crashes after getting FD_CLOSE

### ISSUE THREAD

**Issue by colge02** [obsproject/loganalyzer#60]
I have 24hr live stream on. This can last for days but a some point the (SKY) broadband has an issue (always overnight/early morning) and OBS logs an "FD_CLOSE" (which matches up with some sort of disconnect logged in the Broadband router). 
Although OBS seems to be able to initially handle the disconnect (by going through the retries, it also throws up an 'obs has crashed' popup dialog on the desktop at that time. However since nobody is around in the middle of the night this popup doesn't get actioned AND the stream actually stays active/live! 
When the popup dialog is responded to (by clicking on 'OK') THEN OBS exits, which also then brings down the livestream at that time. I believe this also leaves an OBS64.exe process running in the system (task manager shows more than one OBS process after OBS is restarted).
The crash always seems the same:
Unhandled exception: c0000005
Fault address: 7FFB08906BAF (c:\program files\obs-studio\obs-plugins\64bit\obs-qsv11.dll)
[Crash 2020-09-09 04-54-48.txt](https://github.com/obsproject/loganalyzer/files/5195891/Crash.2020-09-09.04-54-48.txt)
[2020-09-07 15-03-33.txt](https://github.com/obsproject/loganalyzer/files/5195903/2020-09-07.15-03-33.txt)

**Comment by Fenrirthviti** [comment]
This repo is not for support, please use the forums or discord.

https://obsproject.com/help
