### ISSUE TITLE
hilfe benötigt obs/livestream facebookproducer https?

### ISSUE THREAD

**Issue by ArtistCalled** [obsproject/loganalyzer#61]
https://obsproject.com/logs/bP8hetqsiG1D2q-C

**Comment by WizardCM** [comment]
This repository is for bugs with the log analyzer itself. For support, please visit https://obsproject.com/help

**Comment by ArtistCalled** [comment]
> https://obsproject.com/logs/bP8hetqsiG1D2q-C



> Dieses Repository ist für Fehler mit dem Protokollanalysator selbst. Für Unterstützung besuchen Sie bitte https://obsproject.com/help

Hallo. Ich möchte mich bei Ihnen / Euch entschuldigen. Und für die nette Antwort sehr willkommen heissen.
Bin am lernen.
