### ISSUE TITLE
Connection is dropping

### ISSUE THREAD

**Issue by lemeck** [obsproject/loganalyzer#62]
Dear OBS,

I'm experiencing something weird where connection drops on one of my profile here's the log.
"Aborting due to FD_CLOSE, error 10053"
[2020-09-21 22-53-19.txt](https://github.com/obsproject/loganalyzer/files/5256196/2020-09-21.22-53-19.txt)

**Comment by Fenrirthviti** [comment]
This is not for support, please use the forums or discord instead.

https://obsproject.com/help
