### ISSUE TITLE
Game  appearing super choppy during stream

### ISSUE THREAD

**Issue by manbearpiig** [obsproject/loganalyzer#63]
15:41:51.194: CPU Name: AMD Ryzen 9 3950X 16-Core Processor            
15:41:51.195: CPU Speed: 3493MHz
15:41:51.195: Physical Cores: 16, Logical Cores: 32
15:41:51.195: Physical Memory: 32672MB Total, 17137MB Free
15:41:51.195: Windows Version: 10.0 Build 19041 (release: 2004; revision: 508; 64-bit)
15:41:51.195: Running as administrator: false
15:41:51.195: Aero is Enabled (Aero is always on for windows 8 and above)
15:41:51.195: Windows 10 Gaming Features:
15:41:51.195: 	Game Bar: Off
15:41:51.195: 	Game DVR: Off
15:41:51.195: 	Game DVR Background Recording: Off
15:41:51.195: 	Game Mode: Off
15:41:51.196: Sec. Software Status:
15:41:51.197: 	Microsoft Defender Antivirus: enabled (AV)
15:41:51.197: 	Windows Firewall: enabled (FW)
15:41:51.197: Current Date/Time: 2020-10-08, 15:41:51
15:41:51.197: Browser Hardware Acceleration: true
15:41:51.197: Portable mode: false
15:41:51.469: OBS 26.0.2 (64-bit, windows)
15:41:51.469: ---------------------------------
15:41:51.485: ---------------------------------
15:41:51.485: audio settings reset:
15:41:51.485: 	samples per sec: 48000
15:41:51.485: 	speakers:        2
15:41:51.486: ---------------------------------
15:41:51.486: Initializing D3D11...
15:41:51.486: Available Video Adapters: 
15:41:51.488: 	Adapter 0: AMD Radeon RX 5700 XT
15:41:51.488: 	  Dedicated VRAM: 4253294592
15:41:51.488: 	  Shared VRAM:    4244848640
15:41:51.488: 	  PCI ID:         1002:731f
15:41:51.488: 	  Driver Version: 27.20.12031.1000
15:41:51.488: 	  output 0: pos={0, 0}, size={2560, 1440}, attached=true, refresh=144, name=S2719DGF
15:41:51.488: 	  output 1: pos={2560, 0}, size={2560, 1440}, attached=true, refresh=144, name=S2719DGF
15:41:51.490: Loading up D3D11 on adapter AMD Radeon RX 5700 XT (0)
15:41:51.512: D3D11 loaded successfully, feature level used: b000
15:41:51.512: DXGI increase maximum frame latency success
15:41:51.512: D3D11 GPU priority setup failed (not admin?)
15:41:51.853: ---------------------------------
15:41:51.853: video settings reset:
15:41:51.853: 	base resolution:   1920x1080
15:41:51.853: 	output resolution: 1600x900
15:41:51.853: 	downscale filter:  Lanczos
15:41:51.853: 	fps:               60/1
15:41:51.853: 	format:            NV12
15:41:51.853: 	YUV mode:          709/Partial
15:41:51.853: NV12 texture support enabled
15:41:51.858: Audio monitoring device:
15:41:51.858: 	name: Default
15:41:51.858: 	id: default
15:41:51.858: ---------------------------------
15:41:51.861: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
15:41:51.861: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
15:41:52.054: [AMF] Version 2.7.0 loaded (Compiled: 1.4.14.0, Runtime: 1.4.17.0, Library: 1;4;17;0;20.20.31.01;202009230358;CL#2176233).
15:41:52.137: [AMF] [Capability Manager] Testing Direct3D 11 Adapter 'AMD Radeon RX 5700 XT (VEN_1002/DEV_731f/SUB_2398148c/REV_00c1)':
15:41:52.137:   H264/AVC: Supported
15:41:52.137:   H265/HEVC: Supported
15:41:52.137: 
15:41:53.155: Failed to initialize module 'logi_obs_plugin_x64.dll'
15:41:53.156: [obs-browser]: Version 2.8.7
15:41:53.412: Couldn't find VLC installation, VLC video source disabled
15:41:53.416: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
15:41:53.417: No blackmagic support
15:41:53.420: ---------------------------------
15:41:53.420:   Loaded Modules:
15:41:53.420:     win-wasapi.dll
15:41:53.420:     win-mf.dll
15:41:53.420:     win-dshow.dll
15:41:53.420:     win-decklink.dll
15:41:53.420:     win-capture.dll
15:41:53.420:     vlc-video.dll
15:41:53.420:     text-freetype2.dll
15:41:53.420:     rtmp-services.dll
15:41:53.420:     obs-x264.dll
15:41:53.420:     obs-vst.dll
15:41:53.420:     obs-transitions.dll
15:41:53.420:     obs-text.dll
15:41:53.420:     obs-qsv11.dll
15:41:53.420:     obs-outputs.dll
15:41:53.420:     obs-filters.dll
15:41:53.420:     obs-ffmpeg.dll
15:41:53.420:     obs-browser.dll
15:41:53.420:     logi_obs_plugin_x64.dll
15:41:53.420:     image-source.dll
15:41:53.420:     frontend-tools.dll
15:41:53.420:     enc-amf.dll
15:41:53.420:     decklink-ouput-ui.dll
15:41:53.420:     coreaudio-encoder.dll
15:41:53.420: ---------------------------------
15:41:53.420: ==== Startup complete ===============================================
15:41:53.425: All scene data cleared
15:41:53.425: ------------------------------------------------
15:41:53.453: WASAPI: Device 'Speakers (RODECaster Pro Stereo)' [48000 Hz] initialized
15:41:53.453: [Loaded global audio device]: 'Desktop Audio'
15:41:53.470: WASAPI: Device 'Microphone (RODECaster Pro Stereo)' [48000 Hz] initialized
15:41:53.471: [Loaded global audio device]: 'Mic/Aux'
15:41:53.471: [Media Source 'Media Source']: settings:
15:41:53.471: 	input:                   C:/Users/jonni/Downloads/Fire_Embers_23___22s___4k_res.mp4
15:41:53.471: 	input_format:            (null)
15:41:53.471: 	speed:                   100
15:41:53.471: 	is_looping:              yes
15:41:53.471: 	is_hw_decoding:          no
15:41:53.471: 	is_clear_on_media_end:   yes
15:41:53.471: 	restart_on_activate:     yes
15:41:53.471: 	close_when_inactive:     no
15:41:53.500: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)
15:41:53.500: 
15:41:53.676: ---------------------------------
15:41:53.676: [DShow Device: '4kcam'] settings updated: 
15:41:53.676: 	video device: Cam Link 4K
15:41:53.676: 	video path: \\?\usb#vid_0fd9&pid_0066&mi_00#7&33088685&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
15:41:53.676: 	resolution: 3840x2160
15:41:53.676: 	flip: 0
15:41:53.676: 	fps: 29.97 (interval: 333667)
15:41:53.676: 	format: NV12
15:41:53.946: [duplicator-monitor-capture: 'Display Capture'] update settings:
15:41:53.946: 	display: 2 (2560x1440)
15:41:53.946: 	cursor: true
15:41:53.963: Switched to scene 'cam'
15:41:53.965: ------------------------------------------------
15:41:53.965: Loaded scenes:
15:41:53.965: - scene 'Scene':
15:41:53.965: - scene 'cam':
15:41:53.965:     - source: '4kcam' (dshow_input)
15:41:53.965: - scene 'warzone':
15:41:53.965:     - source: 'Game Capture' (game_capture)
15:41:53.965:     - source: '4kcam' (dshow_input)
15:41:53.965:     - source: 'border' (image_source)
15:41:53.965: - scene 'intro':
15:41:53.965:     - source: 'Media Source' (ffmpeg_source)
15:41:53.965:     - source: 'manbearpiig' (text_gdiplus_v2)
15:41:53.965:     - source: 'Text (GDI+)' (text_gdiplus_v2)
15:41:53.965: - scene 'screen':
15:41:53.965:     - source: 'Display Capture' (monitor_capture)
15:41:53.965: ------------------------------------------------
15:43:04.664: ---------------------------------
15:43:04.664: [DShow Device: '4kcam'] settings updated: 
15:43:04.664: 	video device: Cam Link 4K
15:43:04.664: 	video path: \\?\usb#vid_0fd9&pid_0066&mi_00#7&33088685&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
15:43:04.664: 	resolution: 1920x1080
15:43:04.664: 	flip: 0
15:43:04.664: 	fps: 59.94 (interval: 166833)
15:43:04.664: 	format: NV12
15:43:13.653: ---------------------------------
15:43:13.653: [DShow Device: '4kcam'] settings updated: 
15:43:13.653: 	video device: Cam Link 4K
15:43:13.653: 	video path: \\?\usb#vid_0fd9&pid_0066&mi_00#7&33088685&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
15:43:13.653: 	resolution: 1920x1080
15:43:13.653: 	flip: 0
15:43:13.653: 	fps: 59.94 (interval: 166833)
15:43:13.653: 	format: NV12
15:43:15.903: ---------------------------------
15:43:15.903: [DShow Device: '4kcam'] settings updated: 
15:43:15.903: 	video device: Cam Link 4K
15:43:15.903: 	video path: \\?\usb#vid_0fd9&pid_0066&mi_00#7&33088685&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
15:43:15.903: 	resolution: 1920x1080
15:43:15.903: 	flip: 0
15:43:15.903: 	fps: 59.94 (interval: 166833)
15:43:15.903: 	format: NV12
15:43:38.261: User switched to scene 'warzone'
15:44:20.141: ---------------------------------
15:44:20.141: [DShow Device: '4kcam'] settings updated: 
15:44:20.141: 	video device: Cam Link 4K
15:44:20.141: 	video path: \\?\usb#vid_0fd9&pid_0066&mi_00#7&33088685&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
15:44:20.141: 	resolution: 1920x1080
15:44:20.141: 	flip: 0
15:44:20.141: 	fps: 59.94 (interval: 166833)
15:44:20.141: 	format: NV12
15:44:41.474: ---------------------------------
15:44:41.474: [DShow Device: '4kcam'] settings updated: 
15:44:41.474: 	video device: Cam Link 4K
15:44:41.474: 	video path: \\?\usb#vid_0fd9&pid_0066&mi_00#7&33088685&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
15:44:41.474: 	resolution: 1920x1080
15:44:41.474: 	flip: 0
15:44:41.474: 	fps: 59.94 (interval: 166833)
15:44:41.474: 	format: NV12
15:44:46.438: ---------------------------------
15:44:46.438: [DShow Device: '4kcam'] settings updated: 
15:44:46.438: 	video device: Cam Link 4K
15:44:46.438: 	video path: \\?\usb#vid_0fd9&pid_0066&mi_00#7&33088685&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
15:44:46.438: 	resolution: 1920x1080
15:44:46.438: 	flip: 0
15:44:46.438: 	fps: 59.94 (interval: 166833)
15:44:46.438: 	format: NV12
15:44:50.864: User switched to scene 'cam'
15:44:52.149: User switched to scene 'warzone'
15:45:01.226: [game-capture: 'Game Capture'] attempting to hook fullscreen process: ModernWarfare.exe
15:45:01.230: [game-capture: 'Game Capture'] using direct hook
15:45:01.244: [game-capture: 'Game Capture'] graphics-hook.dll loaded against process: ModernWarfare.exe
15:45:01.244: [game-capture: 'Game Capture'] (half life scientist) everything..  seems to be in order
15:45:01.244: [game-capture: 'Game Capture'] Hooked DXGI
15:45:01.253: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:45:01.253: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:45:01.319: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:45:01.326: [game-capture: 'Game Capture'] shared texture capture successful
15:45:03.356: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:45:03.444: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:45:03.444: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:45:03.475: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:45:03.476: [game-capture: 'Game Capture'] shared texture capture successful
15:45:04.296: ---------------------------------
15:45:04.296: [x264 encoder: 'streaming_h264'] preset: slow
15:45:04.296: [x264 encoder: 'streaming_h264'] profile: high
15:45:04.296: [x264 encoder: 'streaming_h264'] settings:
15:45:04.296: 	rate_control: CBR
15:45:04.296: 	bitrate:      5500
15:45:04.296: 	buffer size:  5500
15:45:04.296: 	crf:          0
15:45:04.296: 	fps_num:      60
15:45:04.296: 	fps_den:      1
15:45:04.296: 	width:        1600
15:45:04.296: 	height:       900
15:45:04.296: 	keyint:       120
15:45:04.296: 
15:45:04.296: [x264 encoder: 'streaming_h264'] custom settings: 
15:45:04.296: 	scenecut = 0
15:45:04.301: ---------------------------------
15:45:04.301: [FFmpeg aac encoder: 'avc_aac_stream'] bitrate: 160, channels: 2, channel_layout: 3
15:45:04.301: 
15:45:04.302: [rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmp://live-iad03.twitch.tv/app...
15:45:04.327: [rtmp stream: 'adv_stream'] Interface: Realtek PCIe 2.5GbE Family Controller (ethernet, 1000 mbps)
15:45:05.522: [rtmp stream: 'adv_stream'] Connection to rtmp://live-iad03.twitch.tv/app successful
15:45:05.743: ==== Streaming Start ===============================================
15:45:05.744: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:45:05.860: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:45:05.860: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:45:05.897: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:45:05.909: [game-capture: 'Game Capture'] shared texture capture successful
15:46:27.070: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:46:27.939: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:46:27.939: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:46:27.976: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:46:27.992: [game-capture: 'Game Capture'] shared texture capture successful
15:47:34.624: User switched to scene 'cam'
15:47:34.629: User switched to scene 'Scene'
15:47:34.959: [game-capture: 'Game Capture'] capture stopped
15:47:56.630: User switched to scene 'warzone'
15:48:08.709: [game-capture: 'Game Capture'] attempting to hook fullscreen process: ModernWarfare.exe
15:48:08.715: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:48:08.715: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:48:08.751: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:48:08.759: [game-capture: 'Game Capture'] shared texture capture successful
15:48:15.439: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:48:15.541: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:48:15.541: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:48:15.582: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:48:15.592: [game-capture: 'Game Capture'] shared texture capture successful
15:48:20.770: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:48:20.895: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:48:20.895: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:48:20.942: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:48:20.942: [game-capture: 'Game Capture'] shared texture capture successful
15:48:44.493: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:48:44.581: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:48:44.581: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:48:44.654: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:48:44.659: [game-capture: 'Game Capture'] shared texture capture successful
15:50:02.977: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:50:03.116: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:50:03.116: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:50:03.194: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:50:03.209: [game-capture: 'Game Capture'] shared texture capture successful
15:50:27.023: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:50:27.108: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:50:27.108: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:50:27.181: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:50:27.192: [game-capture: 'Game Capture'] shared texture capture successful
15:50:32.321: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:50:32.439: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:50:32.439: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:50:32.511: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:50:32.526: [game-capture: 'Game Capture'] shared texture capture successful
15:51:01.751: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:51:01.831: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:51:01.831: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:51:01.903: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:51:01.909: [game-capture: 'Game Capture'] shared texture capture successful
15:51:03.122: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:51:03.239: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:51:03.239: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:51:03.299: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:51:03.309: [game-capture: 'Game Capture'] shared texture capture successful
15:51:43.090: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:51:43.168: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:51:43.168: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:51:43.226: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:51:43.242: [game-capture: 'Game Capture'] shared texture capture successful
15:51:48.310: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:51:48.423: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:51:48.423: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:51:48.480: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:51:48.492: [game-capture: 'Game Capture'] shared texture capture successful
15:55:01.622: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:55:01.742: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:55:01.742: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:55:01.804: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:55:01.809: [game-capture: 'Game Capture'] shared texture capture successful
15:55:03.845: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:55:03.978: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:55:03.978: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:55:04.032: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:55:04.042: [game-capture: 'Game Capture'] shared texture capture successful
15:59:23.554: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:59:23.644: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:59:23.644: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:59:23.718: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:59:23.726: [game-capture: 'Game Capture'] shared texture capture successful
15:59:25.945: [rtmp stream: 'adv_stream'] User stopped the stream
15:59:25.945: Output 'adv_stream': stopping
15:59:25.945: Output 'adv_stream': Total frames output: 51349 (51526 attempted)
15:59:25.945: Output 'adv_stream': Total drawn frames: 51407 (51699 attempted)
15:59:25.945: Output 'adv_stream': Number of lagged frames due to rendering lag/stalls: 292 (0.6%)
15:59:25.945: Output 'adv_stream': Number of dropped frames due to insufficient bandwidth/connection stalls: 177 (0.3%)
15:59:25.945: Video stopped, number of skipped frames due to encoding lag: 2/51616 (0.0%)
15:59:25.947: ==== Streaming Stop ================================================
15:59:26.039: warning: 2 frames left in the queue on closing
15:59:32.696: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:59:32.876: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:59:32.876: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:59:33.002: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:59:33.009: [game-capture: 'Game Capture'] shared texture capture successful
15:59:33.194: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:59:33.274: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:59:33.274: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:59:33.347: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:59:33.359: [game-capture: 'Game Capture'] shared texture capture successful
15:59:48.048: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
15:59:48.139: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
15:59:48.139: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
15:59:48.230: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
15:59:48.242: [game-capture: 'Game Capture'] shared texture capture successful
16:01:03.444: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
16:01:03.542: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
16:01:03.542: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
16:01:03.619: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
16:01:03.626: [game-capture: 'Game Capture'] shared texture capture successful
16:01:06.651: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
16:01:06.743: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
16:01:06.743: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
16:01:06.801: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
16:01:06.809: [game-capture: 'Game Capture'] shared texture capture successful
16:02:49.514: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
16:02:49.581: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
16:02:49.581: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
16:02:49.660: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
16:02:49.676: [game-capture: 'Game Capture'] shared texture capture successful
16:02:51.837: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
16:02:51.933: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
16:02:51.933: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
16:02:52.012: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
16:02:52.026: [game-capture: 'Game Capture'] shared texture capture successful
16:04:18.191: [game-capture: 'Game Capture'] ----------------- d3d12 capture freed ----------------
16:04:19.380: [game-capture: 'Game Capture'] We're DXGI1.4 boys!
16:04:19.380: [game-capture: 'Game Capture'] Buffer count: 2, swap effect: 4
16:04:19.441: [game-capture: 'Game Capture'] d3d12 shared texture capture successful
16:04:19.442: [game-capture: 'Game Capture'] shared texture capture successful

**Comment by Fenrirthviti** [comment]
This repository is not for support, please use our forums or discord instead.
