### ISSUE TITLE
gaming-crash-01

### ISSUE THREAD

**Issue by AzekZero** [obsproject/loganalyzer#64]
14:51:14.270: CPU Name: AMD Ryzen 5 5600X 6-Core Processor             
14:51:14.270: CPU Speed: 3693MHz
14:51:14.270: Physical Cores: 6, Logical Cores: 12
14:51:14.270: Physical Memory: 65462MB Total, 59528MB Free
14:51:14.270: Windows Version: 10.0 Build 19042 (release: 2009; revision: 630; 64-bit)
14:51:14.270: Running as administrator: true
14:51:14.270: Aero is Enabled (Aero is always on for windows 8 and above)
14:51:14.270: Windows 10 Gaming Features:
14:51:14.270: 	Game Bar: Off
14:51:14.270: 	Game DVR: Off
14:51:14.270: 	Game DVR Background Recording: Off
14:51:14.270: 	Game Mode: Off
14:51:14.271: 	Hardware GPU Scheduler: On
14:51:14.272: Sec. Software Status:
14:51:14.272: Current Date/Time: 2020-11-15, 14:51:14
14:51:14.272: Browser Hardware Acceleration: true
14:51:14.272: Portable mode: false
14:51:14.583: OBS 26.0.2 (64-bit, windows)
14:51:14.583: ---------------------------------
14:51:14.584: ---------------------------------
14:51:14.584: audio settings reset:
14:51:14.584: 	samples per sec: 48000
14:51:14.584: 	speakers:        2
14:51:14.585: ---------------------------------
14:51:14.585: Initializing D3D11...
14:51:14.585: Available Video Adapters: 
14:51:14.586: 	Adapter 0: NVIDIA GeForce GTX 1060 6GB
14:51:14.586: 	  Dedicated VRAM: 2051014656
14:51:14.586: 	  Shared VRAM:    4256612352
14:51:14.586: 	  PCI ID:         10de:1c03
14:51:14.586: 	  Driver Version: 27.21.14.5709
14:51:14.586: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=144, name=ROG PG248Q
14:51:14.587: 	  output 1: pos={1920, 0}, size={1920, 1200}, attached=true, refresh=59, name=SyncMaster
14:51:14.589: Loading up D3D11 on adapter NVIDIA GeForce GTX 1060 6GB (0)
14:51:14.638: D3D11 loaded successfully, feature level used: b000
14:51:14.639: DXGI increase maximum frame latency success
14:51:14.639: D3D11 GPU priority setup success
14:51:14.954: ---------------------------------
14:51:14.954: video settings reset:
14:51:14.954: 	base resolution:   1920x1080
14:51:14.954: 	output resolution: 1920x1080
14:51:14.954: 	downscale filter:  Bicubic
14:51:14.954: 	fps:               30/1
14:51:14.954: 	format:            NV12
14:51:14.954: 	YUV mode:          709/Partial
14:51:14.954: NV12 texture support enabled
14:51:14.955: Audio monitoring device:
14:51:14.955: 	name: Speakers (Realtek(R) Audio)
14:51:14.955: 	id: {0.0.0.00000000}.{a47fcf9a-02ea-4693-ba09-e7775bf15b08}
14:51:14.955: ---------------------------------
14:51:14.971: [CoreAudio encoder]: Adding CoreAudio AAC encoder
14:51:14.972: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
14:51:14.999: [AMF] Unable to load 'amfrt64.dll', error code 126.
14:51:15.000: [AMF] AMF Test failed due to one or more errors.
14:51:15.000: Failed to initialize module 'enc-amf.dll'
14:51:15.064: [obs-browser]: Version 2.8.7
14:51:15.070: NVENC supported
14:51:15.181: VLC found, VLC video source enabled
14:51:15.239: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
14:51:15.240: No blackmagic support
14:51:15.249: ---------------------------------
14:51:15.249:   Loaded Modules:
14:51:15.249:     win-wasapi.dll
14:51:15.249:     win-mf.dll
14:51:15.249:     win-dshow.dll
14:51:15.249:     win-decklink.dll
14:51:15.249:     win-capture.dll
14:51:15.249:     vlc-video.dll
14:51:15.249:     text-freetype2.dll
14:51:15.249:     rtmp-services.dll
14:51:15.249:     obs-x264.dll
14:51:15.249:     obs-vst.dll
14:51:15.249:     obs-transitions.dll
14:51:15.249:     obs-text.dll
14:51:15.249:     obs-qsv11.dll
14:51:15.249:     obs-outputs.dll
14:51:15.249:     obs-filters.dll
14:51:15.249:     obs-ffmpeg.dll
14:51:15.249:     obs-browser.dll
14:51:15.249:     image-source.dll
14:51:15.249:     frontend-tools.dll
14:51:15.249:     enc-amf.dll
14:51:15.249:     decklink-ouput-ui.dll
14:51:15.249:     coreaudio-encoder.dll
14:51:15.249: ---------------------------------
14:51:15.249: ==== Startup complete ===============================================
14:51:15.276: All scene data cleared
14:51:15.276: ------------------------------------------------
14:51:15.341: WASAPI: Device 'Speakers (NVIDIA RTX Voice)' [48000 Hz] initialized
14:51:15.341: [Loaded global audio device]: 'Desktop Audio'
14:51:15.353: WASAPI: Device 'Snowball (Blue Snowball)' [48000 Hz] initialized
14:51:15.353: [Loaded global audio device]: 'Mic/Aux'
14:51:15.380: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)
14:51:15.380: 
14:51:16.324: Switched to scene 'Scene'
14:51:16.324: ------------------------------------------------
14:51:16.324: Loaded scenes:
14:51:16.324: - scene 'Scene':
14:51:16.324:     - source: 'Game Capture' (game_capture)
14:51:16.324: ------------------------------------------------

**Comment by Fenrirthviti** [comment]
Issues are not for support, use the discord or forums.
